packages:
  - apps/*
  - packages/*
catalogs:
  dev:
    '@esbuild-plugins/node-globals-polyfill': ^0.2.3
    '@next/third-parties': 16.1.1
    '@tailwindcss/postcss': ^4
    '@tailwindcss/vite': ^4
    '@types/node': ^25
    '@types/react': ^19
    '@types/react-dom': ^19
    '@vitejs/plugin-react': ^5.1.2
    globals: ^17.0.0
    tailwindcss: ^4
    tw-animate-css: ^1.4.0
    typescript: ^5
    ts-patch: ^3.3.0
    turbo: ^2.7.4
    tsdown: ^0.19.0
    vite: ^7.3.1
    vite-plugin-html: ^3.2.2
    vite-plugin-singlefile: ^2.3.0
  prod:
    '@next/third-parties': 16.1.1
    '@noble/ciphers': ^2.1.1
    '@noble/curves': ^2.0.1
    '@noble/hashes': ^2.0.1
    '@radix-ui/react-dialog': ^1.1.15
    '@radix-ui/react-dropdown-menu': ^2.1.16
    '@radix-ui/react-hover-card': ^1.1.15
    '@radix-ui/react-label': ^2.1.8
    '@radix-ui/react-popover': ^1.1.15
    '@radix-ui/react-progress': ^1.1.8
    '@radix-ui/react-radio-group': ^1.3.8
    '@radix-ui/react-scroll-area': ^1.2.10
    '@radix-ui/react-select': ^2.2.6
    '@radix-ui/react-separator': ^1.1.8
    '@radix-ui/react-slider': ^1.3.6
    '@radix-ui/react-slot': ^1.2.4
    '@radix-ui/react-switch': ^1.2.6
    '@radix-ui/react-tabs': ^1.1.13
    '@radix-ui/react-tooltip': ^1.2.8
    '@scure/base': ^2.0.0
    '@scure/bip32': ^2.0.1
    '@scure/bip39': ^2.0.1
    buffer: ^6.0.3
    class-variance-authority: ^0.7.1
    clsx: ^2.1.1
    cmdk: ^1.1.1
    eciesjs: ^0.4.15
    input-otp: ^1.4.2
    lucide-react: ^0.562.0
    next: 16.1.1
    next-intl: ^4.7.0
    next-themes: ^0.4.6
    ogl: ^1.0.11
    postcss: ^8.5.3
    react: ^19
    react-dom: ^19
    react-router-dom: ^7.12.0
    react-use-dark-mode: ^2.0.3
    sonner: ^2.0.7
    tailwind-merge: ^3.4.0
